
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/res/res.js",
	"libs/modules/eui/eui.js",
	"libs/modules/tween/tween.js",
	"libs/modules/socket/socket.js",
	"polyfill/promise.js",
	"bin-debug/iData/iNumber/RangeNumber.js",
	"bin-debug/iData/iPet/iPetSkill/PetSkillData.js",
	"bin-debug/iData/iNumber/DamageNumber.js",
	"bin-debug/iData/iPet/iPetSkill/AttackPetSkillData.js",
	"bin-debug/iData/BasicStatus.js",
	"bin-debug/iData/iMonster/Monster.js",
	"bin-debug/iData/iPet/PetStats.js",
	"bin-debug/iData/iPet/PetType.js",
	"bin-debug/iData/iMonster/Boss.js",
	"bin-debug/iData/iMap/MapData.js",
	"bin-debug/iData/iMonster/MonsterData.js",
	"bin-debug/iData/iPet/PetData.js",
	"bin-debug/iData/iPet/PetTypeList.js",
	"bin-debug/iData/iPet/PetDataList.js",
	"bin-debug/iData/iMonster/MonsterList.js",
	"bin-debug/iData/iSkill/Skill.js",
	"bin-debug/iData/iItem/Equipment.js",
	"bin-debug/iData/iMap/Map.js",
	"bin-debug/iPanel/iCell/ButtonCell.js",
	"bin-debug/iData/iItem/EquipmentData.js",
	"bin-debug/blow_sound.js",
	"bin-debug/iData/iMap/MapList.js",
	"bin-debug/iData/iSkill/ActiveSkill.js",
	"bin-debug/iData/iItem/Stat.js",
	"bin-debug/iData/iSkill/SkillData.js",
	"bin-debug/iPanel/iCell/BasicCell.js",
	"bin-debug/iData/iPet/iPetSkill/PassivePetSkillData.js",
	"bin-debug/iData/iItem/WeaponData.js",
	"bin-debug/iData/iItem/WeaponType.js",
	"bin-debug/iData/iMonster/MonsterTitle.js",
	"bin-debug/iData/iMonster/StatMul.js",
	"bin-debug/iData/iItem/EquipType.js",
	"bin-debug/iData/iPlayer/Title.js",
	"bin-debug/iData/iItem/RangeStat.js",
	"bin-debug/iData/iSkill/ActiveSkillData.js",
	"bin-debug/iData/iSkill/iBuff/Buff.js",
	"bin-debug/iData/iSkill/PassiveSkillData.js",
	"bin-debug/tool/Base64.js",
	"bin-debug/iData/iSkill/SkillCategory.js",
	"bin-debug/iData/iPet/iPetSkill/DefencePetSkillData.js",
	"bin-debug/iData/iSkill/SkillType.js",
	"bin-debug/iData/Race.js",
	"bin-debug/iGlobal/Global.js",
	"bin-debug/iPanel/CoverPanel.js",
	"bin-debug/iPanel/iCell/AdvancedCell.js",
	"bin-debug/iData/iItem/Weapon.js",
	"bin-debug/iData/iItem/WeaponCategory.js",
	"bin-debug/iPanel/iCell/InfoWindow.js",
	"bin-debug/iPanel/iScene/BeginScene.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iItem/ItemInnerPanel.js",
	"bin-debug/after_elf.js",
	"bin-debug/after_equip.js",
	"bin-debug/iData/iItem/EquipmentList.js",
	"bin-debug/after_giant.js",
	"bin-debug/after_human.js",
	"bin-debug/after_info.js",
	"bin-debug/iData/iItem/StatList.js",
	"bin-debug/after_item.js",
	"bin-debug/after_pet.js",
	"bin-debug/after_skill.js",
	"bin-debug/after_system.js",
	"bin-debug/after_title.js",
	"bin-debug/after_undeath.js",
	"bin-debug/before_arrow_left.js",
	"bin-debug/before_arrow_right.js",
	"bin-debug/before_dwarf.js",
	"bin-debug/before_elf.js",
	"bin-debug/before_equip.js",
	"bin-debug/before_giant.js",
	"bin-debug/iData/iMonster/MonsterTitleList.js",
	"bin-debug/before_human.js",
	"bin-debug/before_info.js",
	"bin-debug/before_item.js",
	"bin-debug/before_pet.js",
	"bin-debug/before_skill.js",
	"bin-debug/before_system.js",
	"bin-debug/iData/iPet/iPetSkill/PetSkill.js",
	"bin-debug/before_title.js",
	"bin-debug/iData/iPet/iPetSkill/PetSkillList.js",
	"bin-debug/iData/iPet/Pet.js",
	"bin-debug/before_undeath.js",
	"bin-debug/after_arrow_left.js",
	"bin-debug/boss_icon.js",
	"bin-debug/brand_mc.js",
	"bin-debug/buff_burn.js",
	"bin-debug/buff_corrosion.js",
	"bin-debug/iData/iPlayer/TitleList.js",
	"bin-debug/buff_frozen.js",
	"bin-debug/buff_poison.js",
	"bin-debug/button_bagSlot.js",
	"bin-debug/iData/iSkill/iBuff/BuffBurn.js",
	"bin-debug/iData/iSkill/iBuff/BuffCorrosion.js",
	"bin-debug/iData/iSkill/iBuff/BuffFrozen.js",
	"bin-debug/iData/iSkill/iBuff/BuffPoison.js",
	"bin-debug/iData/iSkill/PassiveSkill.js",
	"bin-debug/button_gamble.js",
	"bin-debug/button_help.js",
	"bin-debug/button_map.js",
	"bin-debug/button_petSlot.js",
	"bin-debug/iData/iSkill/SkillDataList.js",
	"bin-debug/button_rebirth.js",
	"bin-debug/button_save.js",
	"bin-debug/iData/RaceList.js",
	"bin-debug/button_shop.js",
	"bin-debug/iGlobal/Player.js",
	"bin-debug/caption_mc.js",
	"bin-debug/iPanel/iBar/Bar.js",
	"bin-debug/com/spikything/utils/MouseWheelTrap.js",
	"bin-debug/doubleCircle.js",
	"bin-debug/facebook_button.js",
	"bin-debug/iPanel/iCell/ButtonGroup.js",
	"bin-debug/iPanel/iCell/EquipButton.js",
	"bin-debug/iPanel/iCell/EquipmentCell.js",
	"bin-debug/font_nesb.js",
	"bin-debug/iPanel/iCell/ItemInfoWindow.js",
	"bin-debug/iPanel/iCell/MenuButton.js",
	"bin-debug/iPanel/iCell/StringCell.js",
	"bin-debug/iPanel/iCell/StringInfoCell.js",
	"bin-debug/iPanel/iCell/StringInfoWindow.js",
	"bin-debug/iPanel/InnerPanel.js",
	"bin-debug/after_dwarf.js",
	"bin-debug/iPanel/iScene/FlickerButton.js",
	"bin-debug/iPanel/iScene/iPanel/AllInfoPanel.js",
	"bin-debug/iPanel/iScene/iPanel/BattleSkillPanel.js",
	"bin-debug/iPanel/iScene/iPanel/ComfirmScene.js",
	"bin-debug/iPanel/iScene/iPanel/HelpPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iAllInfo/AllInfoInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iAllInfo/AllInfoOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iBattleSkill/BattleSkillInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iBattleSkill/BattleSkillOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iShop/GambleCell.js",
	"bin-debug/iPanel/iScene/iPanel/iShop/ShopCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/EquipWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iEquip/EquipCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iItem/ForgeButton.js",
	"bin-debug/after_arrow_right.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iItem/ItemOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iItem/StringInfoButton.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iPet/PetCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iPet/PetIconCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iPet/PetInfoWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iPet/PetInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iPet/PetOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iPet/PetSkillCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/ActiveSkillCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/CombatInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/CombatOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/MagicInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/MagicOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/PassiveInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/PassiveOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/SkillCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSkill/StringButton.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSystem/ClickButton.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSystem/iMap/MapPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iSystem/ToggleBox.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/ItemWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iTitle/TitleCell.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iTitle/TitleInnerPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/iTitle/TitleOutterPanel.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/OtherWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/PetWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/SkillWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/SystemWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/TitleWindow.js",
	"bin-debug/iPanel/iScene/iPanel/iWindow/Window.js",
	"bin-debug/iPanel/iScene/iPanel/LootPanel.js",
	"bin-debug/iPanel/iScene/iPanel/MonsterInfoPanel.js",
	"bin-debug/iPanel/iScene/iPanel/OtherPanel.js",
	"bin-debug/iPanel/iScene/iPanel/PetInfoPanel.js",
	"bin-debug/iPanel/iScene/iPanel/PlayerInfoPanel.js",
	"bin-debug/iPanel/iScene/iPanel/ShopPanel.js",
	"bin-debug/iPanel/iScene/iPanel/SpecialShopPanel.js",
	"bin-debug/iPanel/iScene/MainScene.js",
	"bin-debug/iPanel/iScene/PeopleModel.js",
	"bin-debug/iPanel/iScene/RaceButton.js",
	"bin-debug/iPanel/iScene/RaceScene.js",
	"bin-debug/iPanel/iScene/SaveScene.js",
	"bin-debug/iPanel/MyScrollBar.js",
	"bin-debug/iPanel/OutterPanel.js",
	"bin-debug/Main_fla/MainTimeline.js",
	"bin-debug/Main.js",
	"bin-debug/map_icon.js",
	"bin-debug/map_mc.js",
	"bin-debug/mc_axe.js",
	"bin-debug/mc_blacksmithing.js",
	"bin-debug/mc_body_heavy.js",
	"bin-debug/mc_body_light.js",
	"bin-debug/mc_body_medium.js",
	"bin-debug/mc_bow.js",
	"bin-debug/mc_combat_mastery.js",
	"bin-debug/mc_corrosive_shot.js",
	"bin-debug/mc_counterattack.js",
	"bin-debug/mc_critical_hit.js",
	"bin-debug/mc_crossbow.js",
	"bin-debug/mc_dagger.js",
	"bin-debug/mc_defence.js",
	"bin-debug/mc_equip.js",
	"bin-debug/mc_feet_heavy.js",
	"bin-debug/mc_feet_light.js",
	"bin-debug/mc_feet_medium.js",
	"bin-debug/mc_fireball.js",
	"bin-debug/mc_firebolt.js",
	"bin-debug/mc_forge.js",
	"bin-debug/mc_head_heavy.js",
	"bin-debug/mc_head_light.js",
	"bin-debug/mc_head_medium.js",
	"bin-debug/mc_ice_spear.js",
	"bin-debug/mc_icebolt.js",
	"bin-debug/mc_life_drain.js",
	"bin-debug/mc_lightningbolt.js",
	"bin-debug/mc_lvup.js",
	"bin-debug/mc_magic_mastery.js",
	"bin-debug/mc_mana_shield.js",
	"bin-debug/mc_mirage_missile.js",
	"bin-debug/mc_mode.js",
	"bin-debug/mc_money.js",
	"bin-debug/mc_necklace_accesory.js",
	"bin-debug/mc_range_mastery.js",
	"bin-debug/mc_ring_accesory.js",
	"bin-debug/mc_sceptre.js",
	"bin-debug/mc_shield.js",
	"bin-debug/mc_smash.js",
	"bin-debug/mc_staff.js",
	"bin-debug/mc_sword.js",
	"bin-debug/mc_thunder.js",
	"bin-debug/mc_tome.js",
	"bin-debug/people_use1.js",
	"bin-debug/people_use2.js",
	"bin-debug/pet_attack.js",
	"bin-debug/pet_balance.js",
	"bin-debug/pet_bear.js",
	"bin-debug/pet_defence.js",
	"bin-debug/pet_dragon.js",
	"bin-debug/pet_fox.js",
	"bin-debug/pet_ghost.js",
	"bin-debug/pet_goblin.js",
	"bin-debug/pet_magic.js",
	"bin-debug/pet_rat.js",
	"bin-debug/pet_skeleton.js",
	"bin-debug/pet_spider.js",
	"bin-debug/pet_unicorn.js",
	"bin-debug/pet_wolf.js",
	"bin-debug/pet_zombie.js",
	"bin-debug/pSkill_aggressive.js",
	"bin-debug/pSkill_counterattack.js",
	"bin-debug/pSkill_defensive.js",
	"bin-debug/pSkill_dodge.js",
	"bin-debug/pSkill_double_hit.js",
	"bin-debug/pSkill_fireball.js",
	"bin-debug/pSkill_good_or_evil.js",
	"bin-debug/pSkill_heal.js",
	"bin-debug/pSkill_ice_spear.js",
	"bin-debug/pSkill_injury_resile.js",
	"bin-debug/pSkill_life_drain.js",
	"bin-debug/pSkill_meditation.js",
	"bin-debug/pSkill_protective.js",
	"bin-debug/pSkill_slayer.js",
	"bin-debug/pSkill_strong.js",
	"bin-debug/pSkill_taunt.js",
	"bin-debug/pSkill_thunder.js",
	"bin-debug/pSkill_wisdom.js",
	"bin-debug/pSkill_wise.js",
	"bin-debug/iData/Battle.js",
	"bin-debug/tool/Effect.js",
	"bin-debug/tool/FPSShow.js",
	"bin-debug/tool/HideMessageParticle.js",
	"bin-debug/tool/HideMessageThread.js",
	"bin-debug/tool/MyEvent.js",
	"bin-debug/tool/MyMath.js",
	"bin-debug/yell_sound.js",
	//----auto game_file_list end----
];

var window = this;

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    if(egret_native.featureEnable) {
        //控制一些优化方案是否开启
        var result = egret_native.featureEnable({
            
        });
    }
    egret_native.requireFiles();
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "Main",
		frameRate: 30,
		scaleMode: "showAll",
		contentWidth: 640,
		contentHeight: 1136,
		showPaintRect: false,
		showFPS: false,
		fpsStyles: "x:0,y:0,size:12,textColor:0xffffff,bgAlpha:0.9",
		showLog: false,
		logFilter: "",
		maxTouches: 2,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel("/system/fonts/DroidSansFallback.ttf", 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};